
environment:
  matrix:
    - os: Visual Studio 2015
      env: COMPILER=msvc_x64 COMPILER_VERSION=12.0 TARGET_OS=windows_amd64 FLAVOR=debug
    - os: Visual Studio 2015
      env: COMPILER=msvc_x64 COMPILER_VERSION=12.0 TARGET_OS=windows_amd64 FLAVOR=profile
    - os: Visual Studio 2015
      env: COMPILER=msvc_x64 COMPILER_VERSION=12.0 TARGET_OS=windows_amd64 FLAVOR=final
    - os: Visual Studio 2017
      env: COMPILER=msvc_x64 COMPILER_VERSION=14.0 TARGET_OS=windows_amd64 FLAVOR=debug
    - os: Visual Studio 2017
      env: COMPILER=msvc_x64 COMPILER_VERSION=14.0 TARGET_OS=windows_amd64 FLAVOR=profile
    - os: Visual Studio 2017
      env: COMPILER=msvc_x64 COMPILER_VERSION=14.0 TARGET_OS=windows_amd64 FLAVOR=final

build_script:
  - python waf configure
  - python waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR}
  - python waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --static
  - python waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --dynamic
  - python waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --nomaster

