

environment:
  matrix:
    - COMPILER: msvc_x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: debug
    - COMPILER: msvc_x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: profile
    - COMPILER: msvc_x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: final
    - COMPILER: msvc_x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: debug
    - COMPILER: msvc_x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: profile
    - COMPILER: msvc_x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: final
    - COMPILER: msvc_x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: debug
    - COMPILER: msvc_x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: profile
    - COMPILER: msvc_x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: final
    - COMPILER: msvc_x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: debug
    - COMPILER: msvc_x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: profile
    - COMPILER: msvc_x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: final
    - COMPILER: msvc_x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: debug
    - COMPILER: msvc_x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: profile
    - COMPILER: msvc_x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: final
    - COMPILER: msvc_x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: debug
    - COMPILER: msvc_x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: profile
    - COMPILER: msvc_x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: final
    - COMPILER: msvc_x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: debug
    - COMPILER: msvc_x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: profile
    - COMPILER: msvc_x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: final
    - COMPILER: msvc_x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: debug
    - COMPILER: msvc_x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: profile
    - COMPILER: msvc_x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: final
    - COMPILER: msvc_x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - COMPILER: msvc_x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: profile
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - COMPILER: msvc_x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: final
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - COMPILER: msvc_x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - COMPILER: msvc_x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: profile
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - COMPILER: msvc_x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: final
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017


build_script:
  - set
  - set PATH=%PATH%;C:\MinGW\bin;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\bin;C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
  - python waf configure
  - python waf build:%TARGET_OS%-%COMPILER%-%COMPILER_VERSION%:%FLAVOR%
  - python waf build:%TARGET_OS%-%COMPILER%-%COMPILER_VERSION%:%FLAVOR% --static
  - python waf build:%TARGET_OS%-%COMPILER%-%COMPILER_VERSION%:%FLAVOR% --dynamic
  - python waf build:%TARGET_OS%-%COMPILER%-%COMPILER_VERSION%:%FLAVOR% --nomaster

