
environment:
  matrix:
    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: profile
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_x86
      FLAVOR: final
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: debug
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: profile
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 15.0
      TARGET_OS: windows_amd64
      FLAVOR: final
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 9.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 10.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86_amd64
      COMPILER_VERSION: 11.0
      TARGET_OS: windows_amd64
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 12.0
      TARGET_OS: windows_amd64
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: debug

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: profile

    - COMPILER: msvc
      COMPILER_TARGET: x64
      COMPILER_VERSION: 14.0
      TARGET_OS: windows_amd64
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_amd64
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_amd64
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_amd64
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.4.0
      TARGET_OS: windows_x86
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_x86
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_x86
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_x86
      FLAVOR: final



build_script:
  - set PATH=%PATH%;C:\msys64\usr\bin;C:\msys64\mingw32\bin;C:\msys64\mingw64\bin;C:\cygwin\bin;C:\cygwin64\bin;C:\MinGW\msys\1.0\bin;C:\MinGW\bin;C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\bin;C:\mingw-w64\i686-6.3.0-posix-dwarf-rt_v5-rev1\bin;C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
  - set
  - python waf configure --compilers=%COMPILER%
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR%
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --static
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --dynamic
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --nomaster

