
environment:
  matrix:
    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\bin
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.3.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\msys64\bin;c:\msys64\mingw32\bin;c:\msys64\mingw64\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\MinGW\msys\1.0\bin;C:\MinGW\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\MinGW\msys\1.0\bin;C:\MinGW\bin
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 5.3.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\MinGW\msys\1.0\bin;C:\MinGW\bin
      FLAVOR: final

    - COMPILER: clang
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 4.0.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\Program Files\LLVM\bin;C:\Libraries\llvm-4.0.0\bin;C:\Libraries\llvm-5.0.0\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\cygwin64\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\cygwin64\bin
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: amd64
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_amd64
      COMPILER_PATH: C:\cygwin64\bin
      FLAVOR: final

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\cygwin\bin
      FLAVOR: debug

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\cygwin\bin
      FLAVOR: profile

    - COMPILER: gcc
      COMPILER_TARGET: x86
      COMPILER_VERSION: 6.4.0
      TARGET_OS: windows_x86
      COMPILER_PATH: C:\cygwin\bin
      FLAVOR: final


build_script:
  - set PATH=%COMPILER_PATH%;%PATH%
  - set
  - dir C:\mingw-w64\
  - dir C:\Program Files\LLVM\bin\
  - dir C:\Libraries\llvm-4.0.0\
  - dir C:\Libraries\llvm-5.0.0\
  - python waf configure --compilers=%COMPILER%
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR%
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --static
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --dynamic
  - python waf build:%TARGET_OS%-%COMPILER%_%COMPILER_TARGET%-%COMPILER_VERSION%:%FLAVOR% --nomaster

