language: android

sudo: false

android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-27.0.3
    - ndk-bundle
    - android-26

addons:
  apt:
    packages:
     - ocl-icd-opencl-dev
     - python2.7-dev
     - python3.4-dev
     - libfreetype6-dev
     - libgl1-mesa-dev
     - libgles2-mesa-dev
     - libncurses5-dev
     - zlib1g-dev
     - libopenal-dev
     - liblua5.2-dev
     - libbullet-dev
     - libogg-dev
     - libvorbis-dev


matrix:
  include:
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=debug
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=profile
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=final
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=3.9.0 TARGET_OS=linux_amd64 FLAVOR=debug
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=3.9.0 TARGET_OS=linux_amd64 FLAVOR=profile
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=3.9.0 TARGET_OS=linux_amd64 FLAVOR=final
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=debug
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=profile
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=final
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=debug
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=profile
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=final
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=debug
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=profile
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=final

script:
  - CC= CXX= ./waf configure
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR}
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --static
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --dynamic
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --nomaster
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --nomaster
        --with-included-bullet --with-included-freetype --with-included-lua --with-included-squirrel
        --with-included-zlib --with-included-minizip --with-included-oggvorbis

