language: cpp

sudo: false

os:
 - linux
 - osx

addons:
  apt:
    packages:
     - ocl-icd-opencl-dev
     - python2.7-dev
     - python3.4-dev
     - libfreetype6-dev
     - libgl1-mesa-dev
     - libgles2-mesa-dev
     - libncurses5-dev
     - zlib1g-dev
     - libopenal-dev

script:
  - CC= CXX= ./waf configure
  - ./waf build:all --nomaster

