os:
 - linux
language: cpp
env:
 - OS_NAME=linux
   COMPILER=gcc
   ARCH=amd64
   VERSION=4.6.3
   VARIANT=debug
   MASTER=--nomaster
 - OS_NAME=linux
   COMPILER=gcc
   ARCH=amd64
   VERSION=4.6.3
   VARIANT=profile
   MASTER=
 - OS_NAME=linux
   COMPILER=gcc
   ARCH=amd64
   VERSION=4.6.3
   VARIANT=final
   MASTER=
 - OS_NAME=linux
   COMPILER=clang
   ARCH=amd64
   VERSION=3.4
   VARIANT=debug
   MASTER=--nomaster
 - OS_NAME=linux
   COMPILER=clang
   ARCH=amd64
   VERSION=3.4
   VARIANT=profile
   MASTER=
 - OS_NAME=linux
   COMPILER=clang
   ARCH=amd64
   VERSION=3.4
   VARIANT=final
   MASTER=
 - OS_NAME=windows
   COMPILER=gcc
   ARCH=x86
   VERSION=4.2.1
   VARIANT=debug
   MASTER=--nomaster
 - OS_NAME=windows
   COMPILER=gcc
   ARCH=x86
   VERSION=4.2.1
   VARIANT=profile
   MASTER=
 - OS_NAME=windows
   COMPILER=gcc
   ARCH=x86
   VERSION=4.2.1
   VARIANT=final
   MASTER=
script: CC= CXX= ./waf configure --platforms=$OS_NAME --compilers=$COMPILER $MASTER install:${OS_NAME}_${ARCH}-${COMPILER}_${ARCH}-${VERSION}:${VARIANT}

