language: cpp

sudo: false

addons:
  apt:
    packages:
     - ocl-icd-opencl-dev
     - python2.7-dev
     - python3.4-dev
     - libfreetype6-dev
     - libgl1-mesa-dev
     - libgles2-mesa-dev
     - libncurses5-dev
     - zlib1g-dev
     - libopenal-dev
     - liblua5.2-dev
     - libbullet-dev
     - libogg-dev
     - libvorbis-dev

matrix:
  include:
    - os: linux
      language: android
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=debug
           CONFIGURE_OPTIONS="--android-sdk-path=/usr/local/android-sdk/ --android-ndk-path=/usr/local/android-sdk/ndk-bundle"
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-26
      before_install:
        - yes | /usr/local/android-sdk/tools/bin/sdkmanager "ndk-bundle"
    - os: linux
      language: android
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=profile
           CONFIGURE_OPTIONS="--android-sdk-path=/usr/local/android-sdk/ --android-ndk-path=/usr/local/android-sdk/ndk-bundle"
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-26
      before_install:
        - yes | /usr/local/android-sdk/tools/bin/sdkmanager "ndk-bundle"
    - os: linux
      language: android
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=final
           CONFIGURE_OPTIONS="--android-sdk-path=/usr/local/android-sdk/ --android-ndk-path=/usr/local/android-sdk/ndk-bundle"
      android:
        components:
          - tools
          - platform-tools
          - tools
          - build-tools-27.0.3
          - android-26
      before_install:
        - yes | /usr/local/android-sdk/tools/bin/sdkmanager "ndk-bundle"
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=debug
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=profile
    - os: linux
      env: COMPILER=gcc_amd64 COMPILER_VERSION=4.8.4 TARGET_OS=linux_amd64 FLAVOR=final
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=5.0.0 TARGET_OS=linux_amd64 FLAVOR=debug
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=5.0.0 TARGET_OS=linux_amd64 FLAVOR=profile
    - os: linux
      env: COMPILER=clang_amd64 COMPILER_VERSION=5.0.0 TARGET_OS=linux_amd64 FLAVOR=final
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=debug
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=profile
    - os: linux
      env: COMPILER=gcc_x86 COMPILER_VERSION=4.2.1 TARGET_OS=windows_x86 FLAVOR=final
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=debug
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=profile
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=macosx10.12 FLAVOR=final
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=debug
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=profile
    - os: osx
      env: COMPILER=appleclang COMPILER_VERSION=8.1.0 TARGET_OS=iphonesimulator10.3 FLAVOR=final

script:
  - CC= CXX= ./waf configure ${CONFIGURE_OPTIONS}
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR}
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --static
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --dynamic
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --nomaster
  - ./waf build:${TARGET_OS}-${COMPILER}-${COMPILER_VERSION}:${FLAVOR} --nomaster
        --with-included-bullet --with-included-freetype --with-included-lua --with-included-squirrel
        --with-included-zlib --with-included-minizip --with-included-oggvorbis

