
def options(opt):
	for path in opt.path.listdir():
		if path != 'wscript':
			opt.recurse(path)

def configure(conf):
	for path in conf.path.listdir():
		if path != 'wscript':
			conf.recurse(path)

