version: 2
jobs:
  build:
    docker:
      - image: bugengine/bugengine:latest
    steps:
      - checkout
      - run:
          name: Configure
          command: python waf configure
      - run:
          name: Build GCC Debug
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:debug
      - run:
          name: Build GCC Debug static
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:debug --static
      - run:
          name: Build GCC Debug dynamic
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:debug --dynamic
      - run:
          name: Build GCC Debug without master
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:debug --nomaster
      - run:
          name: Build GCC Profile
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:profile
      - run:
          name: Build GCC Profile static
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:profile --static
      - run:
          name: Build GCC Profile dynamic
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:profile --dynamic
      - run:
          name: Build GCC Profile without master
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:profile --nomaster
      - run:
          name: Build GCC Final
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:final
      - run:
          name: Build GCC Final static
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:final --static
      - run:
          name: Build GCC Final dynamic
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:final --dynamic
      - run:
          name: Build GCC Final without master
          command: python waf build:linux_amd64-gcc_amd64-7.2.1:final --nomaster
      - run:
          name: Build Clang Debug
          command: python waf build:linux_amd64-clang_amd64-4.0.1:debug
      - run:
          name: Build Clang Debug static
          command: python waf build:linux_amd64-clang_amd64-4.0.1:debug --static
      - run:
          name: Build Clang Debug dynamic
          command: python waf build:linux_amd64-clang_amd64-4.0.1:debug --dynamic
      - run:
          name: Build Clang Debug without master
          command: python waf build:linux_amd64-clang_amd64-4.0.1:debug --nomaster
      - run:
          name: Build Clang Profile
          command: python waf build:linux_amd64-clang_amd64-4.0.1:profile
      - run:
          name: Build Clang Profile static
          command: python waf build:linux_amd64-clang_amd64-4.0.1:profile --static
      - run:
          name: Build Clang Profile dynamic
          command: python waf build:linux_amd64-clang_amd64-4.0.1:profile --dynamic
      - run:
          name: Build Clang Profile without master
          command: python waf build:linux_amd64-clang_amd64-4.0.1:profile --nomaster
      - run:
          name: Build Clang Final
          command: python waf build:linux_amd64-clang_amd64-4.0.1:final
      - run:
          name: Build Clang Final static
          command: python waf build:linux_amd64-clang_amd64-4.0.1:final --static
      - run:
          name: Build Clang Final dynamic
          command: python waf build:linux_amd64-clang_amd64-4.0.1:final --dynamic
      - run:
          name: Build Clang Final without master
          command: python waf build:linux_amd64-clang_amd64-4.0.1:final --nomaster
