# set posix specific options

import os

def options(opt):
	osname = os.uname()[0].lower()
	opt.recurse(osname)

def configure(conf):
	osname = os.uname()[0].lower()
	conf.recurse(osname)

def build(bld):
	osname = os.uname()[0].lower()
	bld.recurse(osname)
