# set posix specific options

import os
from Logs import warn

def options(opt):
	osname = os.uname()[0].lower()
	opt.recurse(osname)

def configure(conf):
	osname = os.uname()[0].lower()
	conf.recurse(osname)
