# set SunOS/Solaris specific options
# detect tools : gcc, suncc

import os
from waflib.Logs import warn,pprint
import mak.tools.cross_gcc
import mak.tools.cross_suncc

def options(opt):
	pprint('NORMAL', 'Host system is SunOS/Solaris/OpenSolaris.org')

def configure(conf):
	conf.load('bison flex data', tooldir='mak/tools')
	conf.env['HOST'] = 'sunos'
	conf.env['BUILD_VARIANTS'] = []
	conf.get_available_suncc()
	conf.get_available_gcc()
