#! /usr/bin/env python
# set iPhone(Simulator) specific options


def options(option_context):
    gr = option_context.get_option_group('SDK paths and options')
    gr.add_option('--iphone-sdk-min',
                  action='store',
                  default='',
                  dest='iphone_sdk_min',
                  help='Minimum version of the iPhone SDK to target')
    gr.add_option('--iphone-sdk-max',
                  action='store',
                  default='',
                  dest='iphone_sdk_max',
                  help='Maximum version of the iPhone SDK to target')
    #option_context.recurse('mak/device.py')


def host_configure(configuration_context):
    configuration_context.recurse('mak/host_configure.py', name='host_configure')


def configure(configuration_context):
    configuration_context.recurse('mak/configure.py', name='configure')


def setup(configuration_context):
    configuration_context.recurse('mak/setup.py', name='setup')


def build(build_context):
    build_context.recurse('mak/build.py', name='build')


def deploy(build_context):
    build_context.recurse('mak/deploy.py', name='deploy')


def debug(build_context):
    build_context.recurse('mak/debug.py', name='debug')


def run(build_context):
    build_context.recurse('mak/run.py', name='run')
