# set win32 specific options
# detect tools : msvc, mingw


import os
from waflib.Logs import pprint
import mak.tools.cross_gcc


def options(opt):
	pass

def configure(conf):
	conf.load("bison flex data", tooldir=['mak/tools'])
	conf.env['HOST'] = 'osx'
	conf.env['BUILD_VARIANTS'] = []
	
	paths = ['/Developer/usr/bin', '/Developer-old/usr/bin']
	for l in os.listdir('/Developer/Platforms/'):
		paths.append('/Developer/Platforms/%s/Developer/usr/bin'%l)
	conf.get_available_gcc(paths)

