# set win32 specific options
# detect tools : msvc, mingw


import os
from waflib.Logs import pprint
import mak.tools.cross_gcc

os.environ['PATH'] = '/Developer/usr/bin:/Developer-old/usr/bin:'+os.environ['PATH']
for l in os.listdir('/Developer/Platforms/'):
	os.environ['PATH'] = ('/Developer/Platforms/%s/Developer/usr/bin:'%l)+os.environ['PATH']

def options(opt):
	pass

def configure(conf):
	conf.load("bison flex data", tooldir=['mak/tools'])
	conf.env['HOST'] = 'osx'
	conf.env['BUILD_VARIANTS'] = []
	conf.get_available_gcc()

