# set Linux specific options
# detect tools : clang, llvm, gcc, suncc, icc

import os
import re
from waflib import Configure
from waflib import Options
from waflib.Logs import info,warn,pprint
import mak.tools.cross_gcc
import mak.tools.cross_suncc

def get_available_opencc(conf):
	paths = ['/usr/local', '/opt', '/', '/usr']
	for toolchaindir in paths:
		if os.path.isdir(os.path.join(toolchaindir,'lib','gcc-lib')):
			for target in os.listdir(os.path.join(toolchaindir, 'lib', 'gcc-lib')):
				if target in ['.svn', '.cvs']:
					continue
				for version in os.listdir(os.path.join(toolchaindir, 'lib', 'gcc-lib', target)):
					if version in ['.svn', '.cvs']:
						continue
					if os.path.islink(os.path.join(toolchaindir, 'lib', 'gcc-lib', target, version)):
						continue
					name = add_opencc_to_env(conf, version, os.path.join(toolchaindir), target)


def options(opt):
	pass

def configure(conf):
	conf.load("bison flex data", tooldir=['mak/tools'])
	conf.env['HOST'] = 'linux'
	conf.env['BUILD_VARIANTS'] = []
	conf.get_available_gcc()
	conf.get_available_suncc()

