# set win32 specific options
# detect tools : msvc, mingw


import os
import re
import Configure
import Options
from Logs import info,warn

# gets a list of the GCC toolchains installed
def get_available_gcc(conf):
	toolchaindirs=set([])
	conf.env['GCC_TARGETS'] = []
	for dir in os.environ['PATH'].split(':'):
		toolchaindirs.add(os.path.normpath(os.path.join(dir, '..')))
	for toolchaindir in toolchaindirs:
		if not os.path.isdir(os.path.join(toolchaindir,'lib')):
			continue
		for lib in os.listdir(os.path.join(toolchaindir,'lib')):
			if lib == 'gcc':
				libdir = os.path.join(toolchaindir, 'lib', lib)
			elif lib.startswith('gcc'):
				libdir = os.path.join(toolchaindir, 'lib', lib, 'gcc')
			else:
				continue
			for target in os.listdir(libdir):
				if target in ['.svn', '.cvs']:
					continue
				print target
				for version in os.listdir(os.path.join(libdir, target)):
					print version
					if version in ['.svn', '.cvs']:
						continue
					if os.path.islink(os.path.join(libdir, target, version)):
						continue
					conf.env['GCC_TARGETS'].append((version, toolchaindir, target))

def options(opt):
	pass

def configure(conf):
	conf.check_tool("bison flex data", tooldir=['mak/tools'])
	conf.env['HOST'] = 'freebsd'
	conf.env['BUILD_VARIANTS'] = []
	get_available_gcc(conf)

