# set win32 specific options
# detect tools : msvc, mingw


import os
import re
from waflib.Logs import pprint
import mak.tools.cross_gcc

def options(opt):
	pprint('NORMAL', 'Host system is FreeBSD')

def configure(conf):
	conf.load("bison flex data", tooldir=['mak/tools'])
	conf.env['HOST'] = 'freebsd'
	conf.env['BUILD_VARIANTS'] = []
	conf.get_available_gcc()

